name: Build project after push

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  build:
    # Logic: Only run if it's NOT a PR comment AND it's on issue #1
    runs-on: ubuntu-latest
    
    # Required for modern GitHub Actions to create releases/upload assets
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Check files
        run: ls -al app/build/outputs/apk/debug

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_number }}
          name: ${{ github.event.repository.name }} v${{ github.run_number }}
          # Path to the APK generated in the previous step
          files: app/build/outputs/apk/debug/app-debug.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
