name: Build project on PR

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install JS Dependencies
        run: npm install

      - name: Build Web Assets
        run: npm run build

      - name: Sync Capacitor Android
        run: |
          npx cap sync android

      - name: List files (DIAGNOSTIC)
        # This will show us EXACTLY where gradlew is hiding
        run: find . -name "gradlew"

      - name: Build Debug APK
        run: |
          # We use 'sh' here as a backup if './' fails
          chmod +x gradlew
          sh gradlew assembleDebug --stacktrace

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
